#server: # потр развертывания приложения для работы в Idie
  #port: 7000 # потр развертывания приложения для работы в Idie
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/root # для доступа к БД в рамках docker
    #url: jdbc:postgresql://localhost:1111/root  # для работы с БД через приложение
    username: root
    password: root
  mail:
    default-encoding: UTF-8
    host: smtp.mail.ru
    port: 465
    username: dm_bax@mail.ru # логин от учётки Yandex
    password: BebURVGgR1G0dQ5WhdmM # специальный пароль для приложения
    test-connection: true # проверка подключения при старте приложения
    protocol: smtps
  data:
    redis:
      url: http://localhost:8080/api/v1/users/verification
jwt:
  secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
  issuer: Fitness_Studio_BUL