#server: # потр развертывания приложения для работы в Idie
  #port: 8000 # потр развертывания приложения для работы в Idie
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/root # для доступа к БД в рамках docker
    #url: jdbc:postgresql://localhost:1111/root  # для работы с БД через приложение
    username: root
    password: root
  data:
    redis:
      url: http://localhost:8080/api/v1/users/verification
jwt:
  secret: 
  issuer: Fitness_Studio_BUL
